version: "3.9"

services:
  backend:
    build:
      context: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - backend_volume:/usr/src/app

volumes:
  backend_volume:
